async function insert(req);
async function findAll(req, res);
async function findId(req, res);
async function update(req, res);
async function remove(req, res);
async function discount(req, res);
async function hot(req, res);
async function newProduct(req, res);
async function search(req, res);
async function sort(req, res);